choco install adobereader     --limitoutput
choco install brave    --limitoutput
choco install notepadplusplus --limitoutput    
choco install 7zip			  --limitoutput    
choco install lastpass		  --limitoutput
choco install filezilla		  --limitoutput        
choco install ditto			  --limitoutput    
choco install microsoft-teams --limitoutput
choco install greenshot		  --limitoutput   
choco install slack			  --limitoutput
choco install sysinternals    --limitoutput
